# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Jul 03 02:24:17 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, -1, style=0)
        self.notebookConfigPane = wx.Panel(self.notebook, -1)
        self.notebookFilePane = wx.Panel(self.notebook, -1)
        self.targetDirectoryLabel = wx.StaticText(self, -1, "Directory to Process:")
        self.startAddress = wx.TextCtrl(self, -1, "")
        self.selectDirButton = wx.Button(self, -1, "Select Directory")
        self.titleStaticLine = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.startProcButton = wx.Button(self, -1, "Start")
        self.fileTree = wx.TreeCtrl(self.notebookFilePane, -1, style=wx.TR_HAS_BUTTONS|wx.TR_LINES_AT_ROOT|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.generalSimSliderLabel = wx.StaticText(self.notebookFilePane, -1, "Similarity Grouping Threshold")
        self.fillerPanel5 = wx.Panel(self.notebookFilePane, -1)
        self.compThresholdSlider = wx.Slider(self.notebookFilePane, -1, 1000, 1, 5000, style=wx.SL_HORIZONTAL|wx.SL_TOP)
        self.sliderValueLabel = wx.StaticText(self.notebookFilePane, -1, "1.00")
        self.filePaneFileOpsLabel1 = wx.StaticText(self.notebookFilePane, -1, "Check all items with at least", style=wx.ALIGN_CENTRE)
        self.sliderNumFileforChecking = wx.Slider(self.notebookFilePane, -1, 0, 0, 10, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS|wx.SL_LABELS|wx.SL_LEFT|wx.SL_RIGHT|wx.SL_TOP)
        self.filePaneFileOpsLabel2 = wx.StaticText(self.notebookFilePane, -1, "items in group.")
        self.buttonCheckItems = wx.Button(self.notebookFilePane, -1, "Check Items")
        self.fillerPanel1 = wx.Panel(self.notebookFilePane, -1)
        self.expandAllTreeBranchesButton = wx.Button(self.notebookFilePane, -1, "Expand Tree")
        self.checkAllItemsButton = wx.Button(self.notebookFilePane, -1, "Check All")
        self.collapseAllTreeBranchesButton = wx.Button(self.notebookFilePane, -1, "Collapse Tree")
        self.uncheckAllItemsButton = wx.Button(self.notebookFilePane, -1, "Uncheck All")
        self.fillerPanel2 = wx.Panel(self.notebookFilePane, -1)
        self.buttonMoveFiles = wx.Button(self.notebookFilePane, -1, "Move selected files into new subdirectories")
        self.configTabFilenameCleaningLabel = wx.StaticText(self.notebookConfigPane, -1, "Pre-Comparison Filename Processing")
        self.configTabREFilenameCleanerHeadingLabel = wx.StaticText(self.notebookConfigPane, -1, "Regular Expression")
        self.fillerPanel3 = wx.Panel(self.notebookConfigPane, -1)
        self.filenameCleanerRegexTextCtrl = wx.TextCtrl(self.notebookConfigPane, -1, "")
        self.regexValidLabel = wx.StaticText(self.notebookConfigPane, -1, "1.00")
        self.regexDocLabel = wx.StaticText(self.notebookConfigPane, -1, "This RE is run on the filenames before they are compared. If you need to strip out some common factor from the filenames you're processing, do it here.\nNote: All numbers, underscores, dashes, dots, common file extensions, and any words of 2 characters or less in length are already removed without user intervention.")
        self.fillerPanel4 = wx.Panel(self.notebookConfigPane, -1)
        self.configTabFilenameCleanerHeadingStaticText = wx.StaticText(self.notebookConfigPane, -1, "Text Strip List")
        self.fillerPanel3_copy = wx.Panel(self.notebookConfigPane, -1)
        self.filenameCleanerTextCtrl = wx.TextCtrl(self.notebookConfigPane, -1, "")
        self.stripListValidLabel = wx.StaticText(self.notebookConfigPane, -1, "1.00")
        self.stripListDocLabel = wx.StaticText(self.notebookConfigPane, -1, "Colon (:) separated list of terms to remove from filenames before comparing. Case insensitive.")
        self.fillerPanel4_copy = wx.Panel(self.notebookConfigPane, -1)
        self.configTabFilenameCleanerBracketRemvalStaticText = wx.StaticText(self.notebookConfigPane, -1, "Strip out text in:")
        self.textCleanParenthesesCheckbox = wx.CheckBox(self.notebookConfigPane, -1, "Parentheses - ()")
        self.textCleanBracketsCheckbox = wx.CheckBox(self.notebookConfigPane, -1, "Square Brackets - []")
        self.textCleanCurlyBracketsCheckbox = wx.CheckBox(self.notebookConfigPane, -1, "Curly Braces - {}")
        self.confingTabCompEngineLabel = wx.StaticText(self.notebookConfigPane, -1, "Comparison Engine Variables")
        self.labelWordLengthWeighting = wx.StaticText(self.notebookConfigPane, -1, "Word Length Weighting")
        self.fillerPanel6 = wx.Panel(self.notebookConfigPane, -1)
        self.sliderWordLengthWeighting = wx.Slider(self.notebookConfigPane, -1, 1000, 1, 5000, style=wx.SL_HORIZONTAL|wx.SL_TOP)
        self.valueWordLengthWeighting = wx.StaticText(self.notebookConfigPane, -1, "1.00")
        self.labelStrLengthDifferenceWeighting = wx.StaticText(self.notebookConfigPane, -1, "String Length Diffreence Weighting")
        self.fillerPanel7 = wx.Panel(self.notebookConfigPane, -1)
        self.sliderStrLengthDifferenceWeighting = wx.Slider(self.notebookConfigPane, -1, 1000, 1, 5000, style=wx.SL_HORIZONTAL|wx.SL_TOP)
        self.valueStrLengthDifferenceWeighting = wx.StaticText(self.notebookConfigPane, -1, "1.00")
        self.labelWordLengthDifferenceWeighting = wx.StaticText(self.notebookConfigPane, -1, "Word Length Difference Weighting")
        self.fillerPanel8 = wx.Panel(self.notebookConfigPane, -1)
        self.sliderWordLengthDifferenceWeighting = wx.Slider(self.notebookConfigPane, -1, 1000, 1, 5000, style=wx.SL_HORIZONTAL|wx.SL_TOP)
        self.valueWordLengthDifferenceWeighting = wx.StaticText(self.notebookConfigPane, -1, "1.00")
        self.settingInstructions = wx.StaticText(self.notebookConfigPane, -1, "All settings except the Similarity Grouping Threshold require a new comparison to be run to incorporate value changes.")
        self.statusWindow = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.StatusText = wx.StaticText(self, -1, "Status:")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.startPageEntered, self.startAddress)
        self.Bind(wx.EVT_BUTTON, self.selectDirPressed, self.selectDirButton)
        self.Bind(wx.EVT_BUTTON, self.startDirProcessing, self.startProcButton)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.thresholdSliderAdjusted, self.compThresholdSlider)
        self.Bind(wx.EVT_BUTTON, self.checkItemsWithThreshold, self.buttonCheckItems)
        self.Bind(wx.EVT_BUTTON, self.expandTree, self.expandAllTreeBranchesButton)
        self.Bind(wx.EVT_BUTTON, self.checkAllTreeItems, self.checkAllItemsButton)
        self.Bind(wx.EVT_BUTTON, self.expandTree, self.collapseAllTreeBranchesButton)
        self.Bind(wx.EVT_BUTTON, self.uncheckAllTreeItems, self.uncheckAllItemsButton)
        self.Bind(wx.EVT_BUTTON, self.moveSelectedItemsIntoNewFolders, self.buttonMoveFiles)
        self.Bind(wx.EVT_TEXT, self.checkPreprocessingRE, self.filenameCleanerRegexTextCtrl)
        self.Bind(wx.EVT_TEXT, self.checkPreprocessingRE, self.filenameCleanerTextCtrl)
        self.Bind(wx.EVT_CHECKBOX, self.updateCheckboxesConfigEvt, self.textCleanParenthesesCheckbox)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.wordLengthWeightingAdjusted, self.sliderWordLengthWeighting)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.strLenDifferenceAdjusted, self.sliderStrLengthDifferenceWeighting)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.wordLenDifferenceWeightingAdjusted, self.sliderWordLengthDifferenceWeighting)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("wTree Mapper")
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_BTNFACE))
        self.fillerPanel1.SetMinSize((20, 50))
        self.fillerPanel2.SetMinSize((20,50))
        self.configTabFilenameCleaningLabel.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.confingTabCompEngineLabel.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.statusWindow.SetMinSize((920, 120))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        MainSizer = wx.BoxSizer(wx.VERTICAL)
        configTabMainSizer = wx.BoxSizer(wx.VERTICAL)
        configTabCompEngineSlidersSizer = wx.BoxSizer(wx.VERTICAL)
        specialOptionsGridSizer = wx.FlexGridSizer(6, 2, 0, 0)
        configTabFilenameCleanerSizer = wx.BoxSizer(wx.VERTICAL)
        textStripEnclosingItemCheckboxesSizer = wx.BoxSizer(wx.HORIZONTAL)
        configTabFilenameCleanerGridSizer = wx.FlexGridSizer(3, 2, 0, 0)
        configTabFilenameRECleanerGridSizer = wx.FlexGridSizer(3, 2, 0, 0)
        notebookTreeSizer = wx.BoxSizer(wx.VERTICAL)
        filePaneOperationsSizer = wx.BoxSizer(wx.HORIZONTAL)
        sizerControlItemsButtons = wx.GridSizer(2, 2, 0, 0)
        mainOptionsGridSizer = wx.FlexGridSizer(2, 2, 0, 0)
        titleSizer = wx.BoxSizer(wx.VERTICAL)
        dirTextBoxSizer = wx.BoxSizer(wx.HORIZONTAL)
        titleSizer.Add(self.targetDirectoryLabel, 0, wx.ALL, 5)
        dirTextBoxSizer.Add(self.startAddress, 1, wx.EXPAND, 0)
        dirTextBoxSizer.Add(self.selectDirButton, 0, wx.LEFT, 5)
        dirTextBoxSizer.Add(self.titleStaticLine, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        dirTextBoxSizer.Add(self.startProcButton, 0, 0, 0)
        titleSizer.Add(dirTextBoxSizer, 1, wx.EXPAND, 0)
        MainSizer.Add(titleSizer, 0, wx.EXPAND, 0)
        notebookTreeSizer.Add(self.fileTree, 1, wx.EXPAND, 0)
        mainOptionsGridSizer.Add(self.generalSimSliderLabel, 0, 0, 0)
        mainOptionsGridSizer.Add(self.fillerPanel5, 1, wx.EXPAND, 0)
        mainOptionsGridSizer.Add(self.compThresholdSlider, 0, wx.EXPAND, 0)
        mainOptionsGridSizer.Add(self.sliderValueLabel, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        mainOptionsGridSizer.AddGrowableCol(0)
        notebookTreeSizer.Add(mainOptionsGridSizer, 0, wx.ALL|wx.EXPAND, 10)
        filePaneOperationsSizer.Add(self.filePaneFileOpsLabel1, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        filePaneOperationsSizer.Add(self.sliderNumFileforChecking, 0, 0, 0)
        filePaneOperationsSizer.Add(self.filePaneFileOpsLabel2, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        filePaneOperationsSizer.Add(self.buttonCheckItems, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        filePaneOperationsSizer.Add(self.fillerPanel1, 0, 0, 0)
        sizerControlItemsButtons.Add(self.expandAllTreeBranchesButton, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizerControlItemsButtons.Add(self.checkAllItemsButton, 0, wx.EXPAND, 0)
        sizerControlItemsButtons.Add(self.collapseAllTreeBranchesButton, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizerControlItemsButtons.Add(self.uncheckAllItemsButton, 0, wx.EXPAND, 0)
        filePaneOperationsSizer.Add(sizerControlItemsButtons, 0, wx.EXPAND, 0)
        filePaneOperationsSizer.Add(self.fillerPanel2, 1, wx.EXPAND, 0)
        filePaneOperationsSizer.Add(self.buttonMoveFiles, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        notebookTreeSizer.Add(filePaneOperationsSizer, 0, wx.EXPAND, 0)
        self.notebookFilePane.SetSizer(notebookTreeSizer)
        configTabFilenameCleanerSizer.Add(self.configTabFilenameCleaningLabel, 0, wx.ALL, 3)
        configTabFilenameRECleanerGridSizer.Add(self.configTabREFilenameCleanerHeadingLabel, 0, 0, 0)
        configTabFilenameRECleanerGridSizer.Add(self.fillerPanel3, 1, wx.EXPAND, 0)
        configTabFilenameRECleanerGridSizer.Add(self.filenameCleanerRegexTextCtrl, 0, wx.EXPAND, 0)
        configTabFilenameRECleanerGridSizer.Add(self.regexValidLabel, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        configTabFilenameRECleanerGridSizer.Add(self.regexDocLabel, 0, 0, 0)
        configTabFilenameRECleanerGridSizer.Add(self.fillerPanel4, 1, wx.EXPAND, 0)
        configTabFilenameRECleanerGridSizer.AddGrowableCol(0)
        configTabFilenameCleanerSizer.Add(configTabFilenameRECleanerGridSizer, 0, wx.ALL|wx.EXPAND, 10)
        configTabFilenameCleanerGridSizer.Add(self.configTabFilenameCleanerHeadingStaticText, 0, 0, 0)
        configTabFilenameCleanerGridSizer.Add(self.fillerPanel3_copy, 1, wx.EXPAND, 0)
        configTabFilenameCleanerGridSizer.Add(self.filenameCleanerTextCtrl, 0, wx.EXPAND, 0)
        configTabFilenameCleanerGridSizer.Add(self.stripListValidLabel, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        configTabFilenameCleanerGridSizer.Add(self.stripListDocLabel, 0, 0, 0)
        configTabFilenameCleanerGridSizer.Add(self.fillerPanel4_copy, 1, wx.EXPAND, 0)
        configTabFilenameCleanerGridSizer.AddGrowableCol(0)
        configTabFilenameCleanerSizer.Add(configTabFilenameCleanerGridSizer, 0, wx.ALL|wx.EXPAND, 10)
        textStripEnclosingItemCheckboxesSizer.Add(self.configTabFilenameCleanerBracketRemvalStaticText, 0, 0, 0)
        textStripEnclosingItemCheckboxesSizer.Add(self.textCleanParenthesesCheckbox, 0, wx.LEFT|wx.RIGHT, 5)
        textStripEnclosingItemCheckboxesSizer.Add(self.textCleanBracketsCheckbox, 0, 0, 0)
        textStripEnclosingItemCheckboxesSizer.Add(self.textCleanCurlyBracketsCheckbox, 0, wx.LEFT|wx.RIGHT, 5)
        configTabFilenameCleanerSizer.Add(textStripEnclosingItemCheckboxesSizer, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 10)
        configTabMainSizer.Add(configTabFilenameCleanerSizer, 0, wx.EXPAND, 0)
        configTabCompEngineSlidersSizer.Add(self.confingTabCompEngineLabel, 0, wx.ALL, 3)
        specialOptionsGridSizer.Add(self.labelWordLengthWeighting, 0, 0, 0)
        specialOptionsGridSizer.Add(self.fillerPanel6, 1, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.sliderWordLengthWeighting, 0, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.valueWordLengthWeighting, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        specialOptionsGridSizer.Add(self.labelStrLengthDifferenceWeighting, 0, wx.TOP, 10)
        specialOptionsGridSizer.Add(self.fillerPanel7, 1, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.sliderStrLengthDifferenceWeighting, 0, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.valueStrLengthDifferenceWeighting, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        specialOptionsGridSizer.Add(self.labelWordLengthDifferenceWeighting, 0, wx.TOP, 10)
        specialOptionsGridSizer.Add(self.fillerPanel8, 1, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.sliderWordLengthDifferenceWeighting, 0, wx.EXPAND, 0)
        specialOptionsGridSizer.Add(self.valueWordLengthDifferenceWeighting, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        specialOptionsGridSizer.AddGrowableCol(0)
        configTabCompEngineSlidersSizer.Add(specialOptionsGridSizer, 0, wx.ALL|wx.EXPAND, 10)
        configTabMainSizer.Add(configTabCompEngineSlidersSizer, 1, wx.EXPAND, 0)
        configTabMainSizer.Add(self.settingInstructions, 0, wx.ALL, 5)
        self.notebookConfigPane.SetSizer(configTabMainSizer)
        self.notebook.AddPage(self.notebookFilePane, "File List")
        self.notebook.AddPage(self.notebookConfigPane, "Settings")
        MainSizer.Add(self.notebook, 1, wx.EXPAND, 0)
        MainSizer.Add(self.statusWindow, 0, wx.EXPAND, 0)
        MainSizer.Add(self.StatusText, 0, wx.ALL, 5)
        self.SetSizer(MainSizer)
        MainSizer.Fit(self)
        self.Layout()
        # end wxGlade

    def startPageEntered(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `startPageEntered' not implemented!"
        event.Skip()

    def selectDirPressed(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `selectDirPressed' not implemented!"
        event.Skip()

    def startDirProcessing(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `startDirProcessing' not implemented!"
        event.Skip()

    def thresholdSliderAdjusted(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `thresholdSliderAdjusted' not implemented!"
        event.Skip()

    def checkItemsWithThreshold(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `checkItemsWithThreshold' not implemented!"
        event.Skip()

    def expandTree(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `expandTree' not implemented!"
        event.Skip()

    def checkAllTreeItems(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `checkAllTreeItems' not implemented!"
        event.Skip()

    def uncheckAllTreeItems(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `uncheckAllTreeItems' not implemented!"
        event.Skip()

    def moveSelectedItemsIntoNewFolders(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `moveSelectedItemsIntoNewFolders' not implemented!"
        event.Skip()

    def checkPreprocessingRE(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `checkPreprocessingRE' not implemented!"
        event.Skip()

    def updateCheckboxesConfigEvt(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `updateCheckboxesConfigEvt' not implemented!"
        event.Skip()

    def wordLengthWeightingAdjusted(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `wordLengthWeightingAdjusted' not implemented!"
        event.Skip()

    def strLenDifferenceAdjusted(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `strLenDifferenceAdjusted' not implemented!"
        event.Skip()

    def wordLenDifferenceWeightingAdjusted(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `wordLenDifferenceWeightingAdjusted' not implemented!"
        event.Skip()

# end of class MainFrame


