#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Jul 03 02:24:17 2010

import wx
from MainFrame import MainFrame

if __name__ == "__main__":
    pyFOrg = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame = MainFrame(None, -1, "")
    pyFOrg.SetTopWindow(mainFrame)
    mainFrame.Show()
    pyFOrg.MainLoop()
